apiVersion: v1
kind: Secret
metadata:
  name: ssh-keys
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHddddAgICJxdWF5LmlvIjogewogICAgICAiYXV0aCI6ICccccZ5Y205aVpYSTZUelJVY0hSd1J6Sm5kVEp1WVZWS1pHWmlkRWRDYlRaaWFXSmtNazFHWWt4emVFZGthMDFxYTFsQmRIQnFSWEZ3V0VjMlNYRkdRVE5CUzFGSVJtaFajszd9figKhCjgICBgImVtYWlsIjogIiIKICAgIH0KICB9Cn0=