apiVersion: v1
kind: ServiceAccount
metadata:
  name: visa-processor
  namespace: payments
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: visa-processor-binding
subjects:
  - kind: ServiceAccount
    name: visa-processor
    namespace: payments
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io  