apiVersion: v1
kind: Service
metadata:
  labels:
    app: visa-processor
  name: visa-processor-service
  namespace: payments
spec:
  clusterIP: 172.30.49.69
  clusterIPs:
  - 172.30.49.69
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: visa-processor
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
